<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.3mQSaZM' shared service.

return $this->privates['.service_locator.3mQSaZM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ServiceController::CreerEditEmployer' => ['privates', '.service_locator.JESRXF2', 'get_ServiceLocator_JESRXF2Service.php', true],
    'App\\Controller\\ServiceController::CreerService' => ['privates', '.service_locator.AMLZ17G', 'get_ServiceLocator_AMLZ17GService.php', true],
    'App\\Controller\\ServiceController:CreerEditEmployer' => ['privates', '.service_locator.JESRXF2', 'get_ServiceLocator_JESRXF2Service.php', true],
    'App\\Controller\\ServiceController:CreerService' => ['privates', '.service_locator.AMLZ17G', 'get_ServiceLocator_AMLZ17GService.php', true],
], [
    'App\\Controller\\ServiceController::CreerEditEmployer' => '?',
    'App\\Controller\\ServiceController::CreerService' => '?',
    'App\\Controller\\ServiceController:CreerEditEmployer' => '?',
    'App\\Controller\\ServiceController:CreerService' => '?',
]);
