<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.DbXKXCV' shared service.

return $this->privates['.service_locator.DbXKXCV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'serv' => ['privates', '.errored..service_locator.DbXKXCV.App\\Entity\\Service', NULL, 'Cannot autowire service ".service_locator.DbXKXCV": it references class "App\\Entity\\Service" but no such service exists.'],
], [
    'serv' => 'App\\Entity\\Service',
]);
