<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6jJPrCi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6jJPrCi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6jJPrCi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6jJPrCi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6jJPrCi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6jJPrCi',
    'container.build_id' => 'c5b884bb',
    'container.build_time' => 1563116003,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6jJPrCi');
